# Generated by release script
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := hdcp2x.srm
LOCAL_SRC_FILES := target/product/shieldtablet/etc/hdcpsrm/hdcp2x.srm
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/etc/hdcpsrm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := hdcp1x.srm
LOCAL_SRC_FILES := target/product/shieldtablet/etc/hdcpsrm/hdcp1x.srm
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/etc/hdcpsrm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := hdcp2xtest.srm
LOCAL_SRC_FILES := target/product/shieldtablet/etc/hdcpsrm/hdcp2xtest.srm
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/etc/hdcpsrm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
include $(BUILD_COPY_HEADERS)
